### ISSUE TITLE
error netattack2

### ISSUE THREAD

**Issue by djahrastafaari** [chrizator/netattack2#14]
how to resolve this errror: 
Traceback (most recent call last):
  File "./netattack2.py", line 47, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by hearthacker1** [comment]
occuring error like djahrastafaari please help us to resolve this problem

**Comment by hearthacker1** [comment]
hi sir what up today i am very tried because of your this tool that not work please help us to resolve this bloody problem
root@khalid:~/netattack2# ./netattack2.py
ERROR: Modules missing.
Do you want to automatically install all requirements? (y/n): y
[*] Installing requirements, please stand by...
sudo: pip: command not found

[+] Requirements installed.

**Comment by chrizator** [comment]
Hello,
it seems like you don't have pip installed.

You should be able to fix it by typing:
`sudo apt-get install python-pip` (for python2)
`sudo apt-get install python3-pip` (for python3)

**Comment by kevine02** [comment]
[*] Scanning the network...
Traceback (most recent call last):
  File "netattack2.py", line 579, in <module>
    main()
  File "netattack2.py", line 576, in main
    handle_option(option)
  File "netattack2.py", line 80, in handle_option
    host_scan(False)
  File "netattack2.py", line 214, in host_scan
    hostscan.do_scan(ip_range)
  File "/root/netattack2/src/scan.py", line 61, in do_scan
    name = item["hostnames"][0]["name"]
IndexError: list index out of range

How can I fix this error
