### ISSUE TITLE
Error when starting netattack2.py : TypeError: 'errors' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by utilisateurkli** [chrizator/netattack2#15]
Like issue 14:
scapy is installed,

sudo ./netattack2.py
Traceback (most recent call last):
  File "./netattack2.py", line 47, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

Someone has ever had this problem? Thanks

**Comment by utilisateurkli** [comment]
wifi-pumpkin too, same error...

**Comment by utilisateurkli** [comment]
Solved, simply reinstalled the system.

**Comment by jaikrishnan11** [comment]
How to fix this error?

**Comment by ranafaraznaru** [comment]
anyone have solution??
