### ISSUE TITLE
netattack error

### ISSUE THREAD

**Issue by mtdeason** [chrizator/netattack2#16]
root@kali:~# cd netattack2
root@kali:~/netattack2# ls
CREDITS  LICENSE  README.md  netattack2.py  src
root@kali:~/netattack2# ./netattack2.py 
Traceback (most recent call last):
  File "./netattack2.py", line 47, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by ranafaraznaru** [comment]
if you have fix this issue please help me too

**Comment by x3l51** [comment]
Whats the output for `sudo python2 netattack2.py`?
