### ISSUE TITLE
I get this error. program not running

### ISSUE THREAD

**Issue by waelhaydar** [chrizator/netattack2#5]
Traceback (most recent call last):
  File "netattack2.py", line 2, in <module>
    from src import *
  File "/root/netattack2/src/scan.py", line 3, in <module>
    import netifaces
ImportError: No module named netifaces

**Comment by chrizator** [comment]
I have not yet included an auto installer. Sorry for that.
Type:
`pip install netifaces`

Thank you for reporting.
