### ISSUE TITLE
after entering to interface, when i select category and hit enter i get following error

### ISSUE THREAD

**Issue by PawanBhusal** [chrizator/netattack2#9]
Scanning the network...
Traceback (most recent call last):
  File "./netattack2.py", line 578, in <module>
    main()
  File "./netattack2.py", line 575, in main
    handle_option(option)
  File "./netattack2.py", line 79, in handle_option
    host_scan(False)
  File "./netattack2.py", line 213, in host_scan
    hostscan.do_scan(ip_range)
  File "/home/code/Desktop/hacking/netattack2/src/scan.py", line 43, in do_scan
    nm = nmap.PortScanner()
  File "/usr/lib/python2.7/dist-packages/nmap/nmap.py", line 192, in __init__
    raise PortScannerError('nmap program was not found in path')
nmap.nmap.PortScannerError: 'nmap program was not found in path'

**Comment by chrizator** [comment]
Hello,
python-nmap relies on the pure nmap.
You probably don't have nmap installed, just python-nmap which can't do the work on its own.

You just type:
`apt-get install nmap`

If you are not on Debian, use another packet manager.
However, this should do the job.
Thank you for reporting, I will add this to the requirements.
Greetings,
~ chrizator

**Comment by PawanBhusal** [comment]
I have already install the nmap.I think this is not the problem .I am using ubuntu backbox 4.7

**Comment by chrizator** [comment]
Seems like the path nmap is installed in can't be detected. Could you please send me the output of
`locate nmap`

Thanks
